dist: xenial
env:
  global:
    - CC_TEST_REPORTER_ID=599d62d35ad6a8f7e72dcca84cb343f5c3863a9617ee43eb6dc13d0600bc28e8
language: ruby
sudo: true
services:
  - mysql
  - redis-server
  - xvfb
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - wget http://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - sleep 3
addons:
  chrome: stable
before_install:
  - sudo cp config/secrets.yml.example config/secrets.yml
  - sudo service mysql restart
  - sudo mysql -e "CREATE USER 'exercism_reboot'@'localhost' IDENTIFIED BY 'exercism_reboot'" -u root
  - sudo mysql -e "create database exercism_reboot_test" -u root
  - sudo mysql -e "ALTER DATABASE exercism_reboot_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" -u root
  - sudo mysql -e "GRANT ALL PRIVILEGES ON exercism_reboot_test.* TO 'exercism_reboot'@'localhost'" -u root
install:
  - "bundle install --jobs=3 --retry=3 --deployment"
  - "npm install"
  - "bundle exec rake db:test:prepare"
script:
  - "bundle exec rake test"
  - "bundle exec rake test:system"
cache:
  node_modules: true
  directories:
    - vendor/bundle
branches:
  only:
  - master
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t simplecov
