language: ruby
sudo: true
services:
  - mysql
  - redis-server
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
addons:
  sources:
    - google-chrome
  apt:
    packages:
      - google-chrome-stable
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - sudo mysql -e "CREATE USER 'exercism_reboot'@'localhost' IDENTIFIED BY 'exercism_reboot'" -u root
  - sudo mysql -e "create database exercism_reboot_test" -u root
  - sudo mysql -e "ALTER DATABASE exercism_reboot_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" -u root
  - sudo mysql -e "GRANT ALL PRIVILEGES ON exercism_reboot_test.* TO 'exercism_reboot'@'localhost'" -u root
install:
  - "bundle install"
  - "npm install"
  - "bundle exec rake db:test:prepare"
script:
  - "bundle exec rake test"
  - "bundle exec rake test:system"
cache:
  - bundler
  - node_modules
