default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_unicode_ci
  username: exercism_reboot
  password: exercism_reboot
  host: localhost
  variables:
    sql_mode: traditional

development:
  <<: *default
  database: exercism_reboot_development

test:
  <<: *default
  database: exercism_reboot_test

production:
  <<: *default
  database:
  host:
  username:
  password:
